### ISSUE TITLE
Multiple power tabs:

### ISSUE THREAD

**Issue by TheGentzy** [Karel-Kroeze/RW_Manager#11]
Power Tab 1:
![screenshot 242](https://cloud.githubusercontent.com/assets/7831879/11969705/c4a0e5e0-a8da-11e5-9594-b15cc7013633.png)
Power Tab 2:
![screenshot 243](https://cloud.githubusercontent.com/assets/7831879/11969707/cd665a2a-a8da-11e5-90fb-4e189727648b.png)
Manger Building:
![screenshot 241](https://cloud.githubusercontent.com/assets/7831879/11969711/d4ac7bac-a8da-11e5-928e-f20a844883c4.png)

As you can see thier are duplicate tabs... why? Does it have to do with my manger?

I have all 3 researches.

For those interested, I crushed a ship with a roof to get the AI core...

**Comment by TheGentzy** [comment]
Restarting game removes 2rd power tab. Probably a first time research thing... I dunno.

**Comment by TheGentzy** [comment]
Moving the AI manger re-add the secound tab.

**Comment by TheGentzy** [comment]
![screenshot 247](https://cloud.githubusercontent.com/assets/7831879/11986689/bade1ff4-a98f-11e5-890e-917d19518b7e.png)
I was checking the range for a recipe, then I noticed I got 5 power tabs...

**Comment by TheGentzy** [comment]
Restarted game. Had 1 power tab. Checked in later, had 2. Now I have 3.

Seems the number of power tabs is determined by time game has been running, or at least related. 

Unrelated note: I've had 1 solar flare since I restarted the game, I do recall a few other power outages to the AI manger (due to batteries running out of juice as I improve the power grid). Maybe power outages to the AI manger add tabs?

**Comment by TheGentzy** [comment]
Flipped power off AI manger manually, no new tab was added.

**Comment by Karel-Kroeze** [comment]
the tab is added when the research is completed, I suppose for some reason the game periodically refreshes all the research or something. Anyway, it's a simple fix (check if there is one before adding it), I just haven't gotten to it yet, sorry ;).

**Comment by Karel-Kroeze** [comment]
Fixed in 3267ad0be848d007157c6081320f6dc4fe4c6a8d
